# Docker Compose override for development
# This file extends docker-compose.yml for local development
version: "3.8"

services:
  postgres:
    # Development specific settings
    environment:
      POSTGRES_DB: toptable_games
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Enable logging for development
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    # Mount the entire db folder for easy access to all SQL files
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    # Enable verbose logging for development
    command: postgres -c log_statement=all -c log_destination=stderr

  backend:
    # Development environment variables
    environment:
      NODE_ENV: development
      SERVER_PORT: 4050
      CONNECTION_STRING: postgresql://postgres:postgres@postgres:5432/toptable_games?sslmode=disable
      SESSION_SECRET: development-session-secret-that-is-super-long-and-secure-for-local-testing-only
      REDIS_URL: redis://redis:6379
      CORS_ORIGIN: http://localhost:3000
      # Enable debug logging
      DEBUG: app:*
      LOG_LEVEL: debug
    # Override health check for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4050/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    # Development Redis configuration
    command: redis-server --appendonly yes --loglevel verbose
